apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  namespace: micro-app
spec:
  volumeName: shared-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce  # if using NFS or similar
  resources:
    requests:
      storage: 512Mi
