# Author: Abdalrhman Alkrain
# Year: 2025
# Version: 1.0

# define the app name
name: document-db
namespace: micro-app

#Common
common:
  labels:
    owner: abdalrhman
    env: dev
    app: document-db

# Deployment
document-db:
  restartPolicy: "Always"
  deployment:
    replicas: 1
    expose-port: 3306
    image:
      repository: bitnami
      image-name: mysql
      image-version: "8.0.20"
      container-name: mysql
      imagePullPolicy: IfNotPresent
    volume: 
      mountPath: /var/lib/mysql/
      name: mysql-storage
  service:
    port:
      listener-port: 3306
      expose-port: 3306

  configMap:
    data:
      MYSQL_DATABASE: report-service
      MYSQL_EXTRA_FLAGS: "--lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp"

  secret:
    data:
      MYSQL_USER: adminUser
      MYSQL_PASSWORD: AdminPassword
      MYSQL_ROOT_PASSWORD: AdminPassword

  
  # pv voulme
  pv:
    storage: 5Gi
    path: "/mnt/data/db"
    accessMode: ReadWriteOnce
