# Author: Abdalrhman Alkrain
# Year: 2025
# Version: 1.0

apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "app.name" .}}
  namespace: {{ index .Values.namespace }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
data:
  NEXUS_SECURITY_RANDOMPASSWORD: {{ .Values.nexus.configMap.NEXUS_SECURITY_RANDOMPASSWORD | quote }}
  create-admin-user.groovy: |
    import org.sonatype.nexus.security.user.UserManager
    security.addUser('myadmin', 'Admin', 'User', 'abdalrhmanalkraien@gmail.com', true, 'admin', [UserManager.DEFAULT_ADMIN_ROLE_ID])


  