# Author: Abdalrhman Alkrain
# Year: 2025
# Version: 1.0

{{ $appName := include "app.name" .}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ $appName }}
  namespace: {{ index .Values.namespace }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nexus.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ $appName }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: {{ index .Values.nexus.deployment.strategy.type }}
  template:
    metadata:
      labels:
        {{ include "common.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yml") . | sha256sum }}
    spec:
      restartPolicy: Always
      nodeName: worker-node-2
      containers:
      - image: {{ include "nexus.deployment.image.fullname" . | quote }}
        imagePullPolicy: {{ .Values.nexus.deployment.image.imagePullPolicy }}
        name: {{ index .Values.nexus.deployment.image "container-name" }}
        resources:
          limits: 
            cpu: "500m"
            memory: "1024Mi"
          requests:
            cpu: "250m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /service/rest/v1/status
            port: {{ index .Values.nexus.deployment "expose-port" }}
          initialDelaySeconds: 120    
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 10

        readinessProbe:
          httpGet:
            path: /service/rest/v1/status
            port: {{ index .Values "nexus" "deployment" "expose-port" }}
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 10
                      
        envFrom:
          - configMapRef:
              name: {{ $appName }}
          - secretRef:
              name: {{ $appName }}
        ports:
        - containerPort: {{ index .Values "nexus" "deployment" "expose-port" }}
          name: expose-port
        volumeMounts: 
          - name:  {{ $appName }}
            mountPath: {{ .Values.nexus.deployment.volume.mountPath }}
          - name: init-script
            mountPath: /opt/sonatype/nexus/etc/scripts
            readOnly: true
      volumes: 
        - name: {{ $appName }}
          persistentVolumeClaim:
            claimName: {{ $appName }}
        - name: init-script
          configMap:
            name: {{ $appName }}
            items:
              - key: create-admin-user.groovy
                path: create-admin-user.groovy