apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deploy-run
  namespace: micro-app
spec:
  taskRef:
    name: deploy-helm
  params:
    - name: release-name
      value: arb-report
    - name: chart-path
      value: ./helm-chart
  podTemplate:
    nodeSelector:
      kubernetes.io/hostname: worker-node-2
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: shared-pvc
