apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: git-clone-test-run
  namespace: micro-app
spec:
  taskRef:
    name: git-clone
  params:
    - name: url
      value: https://github.com/Aswarya-cloud/poc-report.git
    - name: revision
      value: develop
  podTemplate:
    nodeSelector:
      kubernetes.io/hostname: worker-node-2
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: shared-pvc
