apiVersion: v2
name: document-service-app
description: the helm chart for document service.
type: application

# This is the chart version. 
version: 0.1.0

# This is the app version, that will install from docker hub or any other image registery.
appVersion: "1.16.0"
