apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-pipelines
spec:
  params:
    - name: url
      type: string
      description: The github repository
    - name: revision
      type: string
      description: The branch or commit
      default: "develop"
  workspaces:
    - name: output
      description: The workspaces where the branch will be cloned
  steps:
    - name: clone
      image: alpine/git:latest
      script: |
        #!/bin/sh
        git clone -b $(params.revision) $(params.url) $(workspaces.output.path)/source
 
