apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-build
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
      description: where the source code
  steps:  
    - name: build
      image: maven:3.9.6-eclipse-temurin-17
      workingDir: /workspace/source/source
      script: | 
        #!/bin/sh
        echo "Building the project using Maven ..."
        mvn clean package -DskipTests -s /root/.m2/settings.xml
      volumeMounts:
        - name: maven-settings
          mountPath: /root/.m2 

volumes:
  - name: maven-settings
    configMap:
      name: maven-settings
