# Author: Abdalrhman Alkrain
# Year: 2025
# Version: 1.0

name: nexus
namespace: micro-app

#Common
common:
  labels:
    owner: abdalrhman
    env: dev
    app: nexus

nexus:

  # Deployment section
  deployment:
    replicas: 1
    image:
      repository: sonatype
      image-name: nexus3
      image-version: latest
      imagePullPolicy: IfNotPresent # could be Always, IfNotPresent, and Never
      container-name: nexus
    expose-port: 8090
    strategy:
      type: RollingUpdate
    volume: 
      mountPath: /sonatype-work/nexus3
      name: nexus-storage

  # Service section
  service:
    port:
      expose-port: 8081
      listener-port: 8081

  # Secret section
  secret:
    NEXUS_ADMIN_PASSWORD: admin123

  # Config map section
  configMap:
    NEXUS_SECURITY_RANDOMPASSWORD: "false"
    
  # Ingress section
  ingress:
    port:
      number: 8081
  
  # pv
  pv:
    storage: 5Gi
    accessMode: ReadWriteOnce
    path: "/mnt/data"

  #pvc
  pvc:
    app: x
  
