# Author: Abdalrhman Alkrain
# Year: 2025
# Version: 1.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "app.name" .}}
  namespace: {{ index .Values.namespace }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ index .Values "document-app" "deployment" "replicas" }}
  selector:
    matchLabels:
      app: {{ include "app.name" .}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: {{ index .Values "document-app" "deployment" "strategy" "type" }}
  template:
    metadata:
      labels:
        {{ include "common.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/documentConfigMap.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/documentSecret.yml") . | sha256sum }}
    spec:
      # restartPolicy: Always
      containers:
      - image:  {{ include "document-app.deployment.image.fullname" . | quote }}
        imagePullPolicy: {{ index .Values "document-app" "deployment" "image" "imagePullPolicy" }} # could be Always, IfNotPresent, and Never
        name: {{ index .Values "document-app" "deployment" "image" "container-name" }}
        resources:
          limits: 
            cpu: "500m"
            memory: "1024Mi"
          requests:
            cpu: "250m"
            memory: "512Mi"
        envFrom:
          - configMapRef:
              name: {{ include "app.name" .}}
          - secretRef:
              name: {{ include "app.name" .}}
        livenessProbe:
          httpGet:
            path: /api/v1/actuator/health/liveness
            port: {{ index .Values "document-app" "deployment" "expose-port" }}
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 10

        readinessProbe:
          httpGet:
            path: /api/v1/actuator/health/readiness
            port: {{ index .Values "document-app" "deployment" "expose-port" }}
          initialDelaySeconds: 100
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 10      
        ports:
        - containerPort:  {{ index .Values "document-app" "deployment" "expose-port" }}
          name:  expose-port
        volumeMounts:
        - mountPath: /data
          name: data
      nodeName: worker-node
      volumes:
        - name: data
          emptyDir: {}
