{{- $podName := include "document-app.podName" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "document-service.app.name" .}}
  namespace: {{ index .Values "document-app" "namespace" }}
  labels:
    {{ include "document-app.labels" . | nindent 4 }}
spec:
  replicas: {{ index .Values "document-app" "deployment" "replicas" }}
  selector:
    matchLabels:
      app:  {{ $podName }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: {{ index .Values "document-app" "deployment" "strategy" "type" }}
  template:
    metadata:
      labels:
        app: {{ $podName }}
        owner: {{ index .Values "document-app" "labels" "owner" }}
        env: {{ index .Values "document-app" "labels" "env" }}
    spec:
      # restartPolicy: Always
      containers:
      - image:  {{ include "document-app.deployment.image.fullname" . | quote }}
        imagePullPolicy: {{ index .Values "document-app" "deployment" "image" "imagePullPolicy" }} # could be Always, IfNotPresent, and Never
        name: {{ index .Values "document-app" "deployment" "image" "container-name" }}
        resources:
          limits: 
            cpu: "500m"
            memory: "1024Mi"
          requests:
            cpu: "250m"
            memory: "512Mi"
        envFrom:
          - configMapRef:
              name: document-app-map
          - secretRef:
              name: document-app-secret
        livenessProbe:
          httpGet:
            path: /api/v1/actuator/health/liveness
            port: {{ index .Values "document-app" "deployment" "expose-port" }}
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 10

        readinessProbe:
          httpGet:
            path: /api/v1/actuator/health/readiness
            port: {{ index .Values "document-app" "deployment" "expose-port" }}
          initialDelaySeconds: 100
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 10      
        ports:
        - containerPort:  {{ index .Values "document-app" "deployment" "expose-port" }}
          name:  expose-port
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
