apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "document-service.app.name" .}}
  namespace: {{ index .Values "document-app" "namespace" }}
  labels:
    {{ include "document-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  data.username: {{ index .Values "document-app" "secret" "data" "data.username"}}
  data.password: {{ index .Values "document-app" "secret" "data" "data.password"}}
