# Author: Abdalrhman Alkrain
# Year: 2025
# Version: 1.0

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ include "document-service.app.name" .}}
  namespace: {{ index .Values "document-app" "namespace" }}
  labels:
    {{ include "document-app.labels" . | nindent 4 }}
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: micro-app
  
spec:
  rules:
    - host: abed.local
      http: 
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "document-service.app.name" .}}
                port:
                  number: {{ index .Values "document-app" "deployment" "expose-port" }}
