# Author: Abdalrhman Alkrain
# Year: 2025
# Version: 1.0

{{ $appName := include "app.name" . }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ $appName }}
  namespace: {{ index .Values.namespace }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
  
spec:
  rules:
    - host: abed.local
      http: 
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $appName }}
                port:
                  number: {{ index .Values "document-app" "service" "port" "expose-port" }}
