# Author: Abdalrhman Alkrain
# Year: 2025
# Version: 1.0

{{ $appName := include "app.name" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ $appName }}
  namespace: {{ index .Values.namespace }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ index .Values "document-db" "deployment" "replicas" }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yml") . | sha256sum }}
      labels:
        {{ include "common.labels" . | nindent 8 }}
    spec: 
      restartPolicy: {{ index .Values "document-db" "deployment" "restartPolicy" }} 
      containers:
        - image: {{ include "document-db.deployment.image.fullname" . | quote }}
          name: {{ index .Values "document-db" "deployment" "image" "container-name" }}
          imagePullPolicy: {{ index .Values "document-db" "deployment" "image" "imagePullPolicy" }}
          resources:  
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "250m"
              memory: "512Mi"
          env:
            {{ include "document-db.env" . | nindent 10 }}
          ports:
            - containerPort: {{ index .Values "document-db" "deployment" "expose-port" }}
              name: expose-port
          volumeMounts:
            - name:  {{ $appName }}
              mountPath:  {{ index .Values "document-db" "deployment" "volume" "mountPath" }}
      nodeName: worker-node
      volumes:
        - name: {{ $appName }}
          persistentVolumeClaim:
            claimName: {{ $appName }}
          



          


