# Author: Abdalrhman Alkrain
# Year: 2025
# Version: 1.0

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "document-db.app.name" .}}
  namespace: {{ index .Values "document-db" "namespace" }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
spec: 
  accessModes:
    - {{ index .Values "document-db" "pv" "accessMode"}} 
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""