# Author: Abdalrhman Alkrain
# Year: 2025
# Version: 1.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-db.app.name" .}}
  namespace: {{ index .Values "document-db" "namespace" }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_USER: {{ index .Values "document-db" "secret" "data" "MYSQL_USER" }}
  MYSQL_PASSWORD: {{ index .Values "document-db" "secret" "data" "MYSQL_PASSWORD" }}
  MYSQL_ROOT_PASSWORD: {{ index .Values "document-db" "secret" "data" "MYSQL_ROOT_PASSWORD" }}


