apiVersion: v1
kind: ConfigMap
metadata:
  name: document-db-map
  namespace: micro-app
  labels:
    owner: abdalrhman
    env: dev
    app: document-app
data:
  MYSQL_DATABASE: report-service
  MYSQL_EXTRA_FLAGS: "--lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp"
