apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: document-pvc-app
  namespace: micro-app
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""