apiVersion: v1
kind: Secret
metadata:
  name: document-app-secret
  namespace: micro-app
  labels:
    app: document-app
    owner: abdalrhman
    env: dev
type: Opaque
stringData:
  data.username: adminUser
  data.password: AdminPassword
