apiVersion: v1
kind: ConfigMap
metadata:
  name: document-app-map
  namespace: micro-app
  labels:
    app: document-app
    owner: abdalrhman
    env: dev
data:
  data.url: jdbc:mysql://db-service-app.micro-app.svc.cluster.local:3306/report-service?autoReconnect=true&useUnicode=true&character
  _JAVA_OPTIONS: -Xmx2048m -Xms256m
  profile.active: dev