apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  document-service-ingress
  labels:
    app: document-service-ingress
    owner: abdalrhman
    env: dev
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: micro-app
  
spec:
  rules:
    - host: abed.local
      http: 
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: document-service-app
                port:
                  number: 8085
