apiVersion: v1
kind: PersistentVolume
metadata:
  name:  {{ include "document-service.app.name" .}}
  namespace: {{ index .Values "document-app" "namespace" }}
  labels:
    {{ include "document-app.labels" . | nindent 4 }}
spec: 
  capacity: 
    storage: {{ index .Values "document-app" "pv" "storage"}}
  accessModes: 
    - {{ index .Values "document-app" "pv" "accessMode"}} 
  persistentVolumeReclaimPolicy: Retain # keep the data safe after delete the pvc
  storageClassName: ""
  hostPath:
    path: {{ index .Values "document-app" "pv" "path"}}
  
