apiVersion: v1
kind: PersistentVolume
metadata: 
  name: db-document-service
  namespace: micro-app
  labels:
    app: db-document-service
    owner: abdalrhman
    env: dev
spec: 
  capacity: 
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain # keep the data safe after delete the pvc
  storageClassName: ""
  hostPath:
    path: "/mnt/data/db"
  
