apiVersion: v1
kind: Service
metadata:
  name: { .Values.document-app.deployment.labels.name }
  namespace: { .Values.document-app.namespace }
  labels:
    app: { .Values.document-app.labels.app }
    owner: { .Values.document-app.labels.owner }
    env: { .Values.document-app.labels.dev }
spec:
  selector:
    app:  { .Values.document-app.labels.pod-name }
  type:  ClusterIP
  ports:
  - name:  external-port
    port:  { .Values.documnet-app.service.port.expose-port }
    targetPort:  { .Values.documnet-app.service.port.listener-port }
